### ISSUE TITLE
bug: UI crashes when Flow Modal closes with 'Done' click

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/rea-playspace#46]
```
DataStoreBase.ts:33 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at DataStore.getCursor (DataStoreBase.ts:33:43)
    at getFirstCommitmentOrEvent (flows.ts:51:16)
```

**Comment by shanedeeodonnell** [comment]
temp workaround -> https://github.com/lightningrodlabs/rea-playspace/pull/48

@adaburrows

**Comment by adaburrows** [comment]
This is what happens from the user's POV, but what's really happening is none of the commitment flow objects are being saved with the edge. This only effects commitments at the moment, I was able to save an event with an edge successfully. The code that handles updates for the vfPath array of the DisplayEdge needs to be moved into the modal code, and removed from the FlowCanvas.

**Comment by shanedeeodonnell** [comment]
Potentially related to this: I think having form validation would help a lot here. There are some fields that are required deeper in the code like `getLabelForEdge()` in `flows.ts` requires provider and receiver but are not validated on form submit. If I don't both with creating a vf:agent, then there are no provider/receivers. Commenting here because these errors get caught in the try/catch implemented in https://github.com/lightningrodlabs/rea-playspace/pull/48 above.

**Comment by adaburrows** [comment]
The root of the problem stems from me trying to get this out as fast as possible to demo and cutting corners. When I was looking at the code I was going to merge, I saw this as a possibility. Basically, right now, the code creates the display node even if it shouldn't. That likely covers part of it. The other part of it is the UI shows that something's are selected, even if they aren't. I think this is a issue either with Shoelace or the way we don't have a default blank value in the select boxes. Then lastly, yes, form validation would go a long way. Again, not implemented due to rushing the demo.
